### ISSUE TITLE
Adminer

### ISSUE THREAD

**Issue by gaydabura** [skilld-labs/skilld-docker-container#1]
Add adminer container to be able access db as a replacement for phpmyadmin one.
Such container should be based on alpine linux. See https://github.com/clue/docker-adminer/issues/16

**Comment by gaydabura** [comment]
@jbguerraz check https://hub.docker.com/r/dockette/adminer/tags/
committed in 4f3515fd0d963216089e0cfd8773f41e73007bf5

**Comment by andypost** [comment]
I think it much easy just mount `adiner.php` into container

**Comment by gaydabura** [comment]
you may enable it using https://github.com/skilld-labs/skilld-docker-container/blob/master/src/docker/docker-compose.override.yml.default 
Copy file to docker-compose.override.yml and uncomment lines you need.
