### ISSUE TITLE
Add SITE_MAIL to .env and to Makefile

### ISSUE THREAD

**Issue by dkovalskiy-skilld** [skilld-labs/skilld-docker-container#12]
We need to add new parameter SITE_MAIL to .env to use it in Makefile in reinstall section.
it will look like 
...
docker-compose exec php drush si $(PROFILE_NAME) --db-url=mysql://d8:d8@mysql/d8 --account-pass=admin -y --site-name="$(SITE_NAME)" --site-mail="$(SITE_MAIL)"; \
...

We need it to set site mail of the project, because mail from system.site.yml is ommited during drush si.

**Comment by gaydabura** [comment]
https://github.com/skilld-labs/skilld-docker-container/pull/61
