### ISSUE TITLE
Issue with build path 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/skilld-docker-container#16]
Makefile contains 

`
build: clean
	mkdir -p build
	mkdir -p /dev/shm/${COMPOSE_PROJECT_NAME}_mysql
	cp src/drush_make/*.make.yml build/
`
would be cool to have /dev/shm/ path configurable and same with docker compose volume path
`    volumes:
      - /dev/shm/${COMPOSE_PROJECT_NAME}_mysql:/var/lib/mysql:Z
`

**Comment by nabiyllin** [comment]
I agree!

**Comment by andypost** [comment]
Yep good idea not only for macos

**Comment by gaydabura** [comment]
https://github.com/skilld-labs/skilld-docker-container/pull/61
