### ISSUE TITLE
Solr doesn't start automatically after reboot (but other containers do)

### ISSUE THREAD

**Issue by nicolas-guerrier** [skilld-labs/skilld-docker-container#327]
We could add a commented line in docker/docker-compose.yml to make php container depend on solr (as it is for redis, for example), to uncomment in case solr is needed.

**Comment by andypost** [comment]
It's written in service defaults https://github.com/skilld-labs/skilld-docker-container/blob/master/docker/docker-compose.yml#L37

Probably you just need to upgrade definition https://github.com/skilld-labs/skilld-docker-container/blob/master/docker/docker-compose.yml#L5

I bet it could be closed

**Comment by andypost** [comment]
Solr now using restart option, so closing as outdated

```
#  solr:
#    <<: *service-defaults
```
