### ISSUE TITLE
make clean - .env IPRANGE

### ISSUE THREAD

**Issue by jbguerraz** [skilld-labs/skilld-docker-container#4]
When doing a make clean I believe it should remove the "IPRANGE" var from .env

**Comment by gaydabura** [comment]
Actually we should not, because we need to keep IP for next build. In this case you may add ip to hosts and reuse same ip for every re/build

**Comment by jbguerraz** [comment]
It makes sens. But then don't add it if it's already there.

**Comment by gaydabura** [comment]
fixed

**Comment by gaydabura** [comment]
https://github.com/skilld-labs/skilld-docker-container/pull/61 reworked
