### ISSUE TITLE
Move to compose v2 before June'23

### ISSUE THREAD

**Issue by andypost** [skilld-labs/skilld-docker-container#436]
There's things to update

- readme about install
- replace `s/docker-compose/docker compose` and check it works
- decide if tag release before merge

Details https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/

**Comment by nicolas-guerrier** [comment]
On last my fresh Fedora install, I use only `docker compose` plugin and created a shell script in `/usr/local/bin/docker-compose`, containing :

```
#! /bin/sh
docker compose "$@"
```

Got no issue with SDC installs so far, so I guess it gonna be easy to move on to docker compose plugin.

**Comment by nicolas-guerrier** [comment]
Regarding Readme, I didn't update it yet. I guess we need to add a "Dependencies" section (not only about docker[-]compose but also make etc.) before "Quickstart".

Another thought : for BC purpose, we may add some code in Makefile to detect if compose plugin exists & wrap the calls with it, with right version.

Or, if we want to keep Makefile "clean" : copy a shell script (like the one i described above) in $HOME/.local/bin (unsure about compatibility on different installs (Mac? ;)) though)

**Comment by andypost** [comment]
I think checking of old binary could be done but may affect performance as there's sub-make calls which will restart this detection 

++ to describe dependencies.

**Comment by andypost** [comment]
About MacOS we already using comments but some of it could be moved to readme like 
-  https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L51
- https://wodby.com/docs/stacks/drupal/local#docker-for-mac

**Comment by andypost** [comment]
https://developers.redhat.com/articles/2023/05/23/podman-desktop-now-generally-available

GA of podman announced

**Comment by andypost** [comment]
Filed upgrade of manifest https://github.com/skilld-labs/skilld-docker-container/issues/451
