### ISSUE TITLE
Plural formulae missing in fr.po file

### ISSUE THREAD

**Issue by nicolas-guerrier** [skilld-labs/skilld-docker-container#442]
In header of po file we need to add the plural formula (see https://www.drupal.org/community/contributor-guide/reference-information/localize-drupal-org/working-with-offline/po-and-pot-files#s-plural-forms ), right now it's missing.

(Reference for other languages : http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html )

**Comment by andypost** [comment]
Yes, this header is needed according to https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

**Comment by andypost** [comment]
The `\n` is needed too)
