### ISSUE TITLE
Drupal console

### ISSUE THREAD

**Issue by nabiyllin** [skilld-labs/skilld-docker-container#6]
I suggest to add to new infra great new tool is "Drupal console" for acceleration of process development. Just add and comment it, b\c it tool need only back-end developers.
https://hub.docker.com/r/drupalconsole/console/
https://drupalconsole.com/

**Comment by andypost** [comment]
For code generation better use https://github.com/Chi-teck/drupal-code-generator

**Comment by nabiyllin** [comment]
I did not reach before though marked out for itself him. Which reason?

**Comment by andypost** [comment]
Console still not so stable...
So having separate container with "volumes-from web" works

**Comment by nabiyllin** [comment]
What you think about code-generator in generally, it can exist at us and whether there is in it a need in your opinion?

**Comment by gaydabura** [comment]
Using docker-compose.override.yml you may add as may container as you want.
