### ISSUE TITLE
Drupal admin credentials

### ISSUE THREAD

**Issue by jbguerraz** [skilld-labs/skilld-docker-container#88]
It would be great to output the admin password from `make info` command.
Would btw, be cool to be store the default password in `.env.default` so one could eventually change it (at least locally).

**Comment by davidferlay** [comment]
Good point, I know where to find exemple of that. I'll work on it in due time

**Comment by davidferlay** [comment]
https://github.com/skilld-labs/skilld-docker-container/pull/114
